language: node_js
node_js: stable
branches:
  only:
  - hexo
before_script:
  - npm install -g gulp
install:
- npm install
script:
- hexo clean 
- hexo g

after_script:
  - cd ./public
  - git init
  - git config --global user.name 'wencaizhang'
  - git config --global user.email '1052642137@qq.com'
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https:5bcc13de2809632cdeecba8d119f84240c38b5e5@github.com/wencaistorm/wencaistorm.github.io.git" master:master

env:  
 global:   
   - GH_REF: github.com/wencaistorm/wencaistorm.github.io.git
