language: node_js
node_js: stable
branches:
  only:
  - hexo
before_script:
  - echo "hello wencai"
install:
- npm install -g gulp 
- npm install
script:
- hexo clean && hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "wencaistorm"
  - git config user.email "1052642137@qq.com"
  - git add -A
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

env:  
 global:   
   - GH_REF: github.com/wencaistorm/wencaistorm.github.io.git
