language: node_js
node_js: stable

before_install:
– openssl aes-256-cbc -K encrypted_2230b7a2bdc5_key -iv encrypted_2230b7a2bdc5_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
– chmod 600 ~/.ssh/id_rsa
– eval $(ssh-agent)
– ssh-add ~/.ssh/id_rsa
– cp .travis/ssh_config ~/.ssh/config
– npm install -g hexo-cli # 安装 hexo
– git clone https://github.com/wencaistorm/next-m.git themes/next

install:
    - npm install

before_script:
    - git config --global user.name 'wencaistorm'
    - git config --global user.email '1052642137@qq.com'

script:
    - hexo generate

after_success:
    - hexo d