language: node_js
node_js: stable

before_install:
    - npm install -g hexo

install:
    - npm install

before_script:
    - git config --global user.name 'wencaistorm'
    - git config --global user.email '1052642137@qq.com'

script:
    - hexo generate

after_success:
    - hexo d